In [301]:
include("../src/test.jl")

┌ Warning: Assignment to `A` in soft scope is ambiguous because a global variable by the same name exists: `A` will be treated as a new local. Disambiguate by using `local A` to suppress this warning or `global A` to assign to the existing global variable.
└ @ nothing c:\Users\sayeg\Insync\sayeg@ciencias.unam.mx\Google Drive\Backup\Maestria\tesis\geometricProteinFolding\src\scalarRootFinding.jl:154
┌ Warning: Assignment to `A` in soft scope is ambiguous because a global variable by the same name exists: `A` will be treated as a new local. Disambiguate by using `local A` to suppress this warning or `global A` to assign to the existing global variable.
└ @ nothing c:\Users\sayeg\Insync\sayeg@ciencias.unam.mx\Google Drive\Backup\Maestria\tesis\geometricProteinFolding\src\scalarRootFinding.jl:170
┌ Warning: Assignment to `A` in soft scope is ambiguous because a global variable by the same name exists: `A` will be treated as a new local. Disambiguate by using `local A` to suppress this warn

In [3]:
using Distributions
using Plots
plotlyjs()
scatter(1:10,1:10,1:10)

HTML{String}("<script>\n// Immediately-invoked-function-expression to avoid global variables.\n(function() {\n    var warning_div = document.getElementById(\"webio-warning-9752839496947392189\");\n    var hide = function () {\n        var script = document.getElementById(\"webio-setup-12696814918187790037\");\n        var parent = script && script.parentElement;\n        var grandparent = parent && parent.parentElement;\n        if (grandparent) {\n            grandparent.style.display = \"none\";\n        }\n        warning_div.style.display = \"none\";\n    };\n    if (typeof Jupyter !== \"undefined\") {\n        console.log(\"WebIO detected Jupyter notebook environment.\");\n        // Jupyter notebook.\n        var extensions = (\n            Jupyter\n            && Jupyter.notebook.config.data\n            && Jupyter.notebook.config.data.load_extensions\n        );\n        if (extensions && extensions[\"webio-jupyter-notebook\"]) {\n            // Extension already loaded.\n            console.log(\"Jupyter WebIO nbextension detected; not loading ad-hoc.\");\n            hide();\n            return;\n        }\n    } else if (window.location.pathname.includes(\"/lab\")) {\n        // Guessing JupyterLa\n        console.log(\"Jupyter Lab detected; make sure the @webio/jupyter-lab-provider labextension is installed.\");\n        hide();\n        return;\n    }\n})();\n\n</script>\n<p\n    id=\"webio-warning-9752839496947392189\"\n    class=\"output_text output_stderr\"\n    style=\"padding: 1em; font-weight: bold;\"\n>\n    Unable to load WebIO. Please make sure WebIO works for your Jupyter client.\n    For troubleshooting, please see <a href=\"https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/\">\n    the WebIO/IJulia documentation</a>.\n    <!-- TODO: link to installation docs. -->\n</p>\n")

In [302]:
P = helix(e0_l,Point(2.0,2.0,2.0),8,r=2e-2,nturn=2)

PolygonalChain(Point[Point{Float64}(0.0, 0.0, 0.0), Point{Float64}(0.2114003107761841, 0.24152243072383986, 0.21374392516664267), Point{Float64}(0.4241059037871633, 0.4807169714616435, 0.4285104580845265), Point{Float64}(0.6392646249663022, 0.715536510115688, 0.6451988649180097), Point{Float64}(0.8577284367855696, 0.9444616244077055, 0.8644766054733913), Point{Float64}(1.0799506590077919, 1.1666838466299279, 1.0866988276956138), Point{Float64}(1.3059312916329688, 1.3822031767823546, 1.3118655315846763), Point{Float64}(1.5352170148982744, 1.5918280825727547, 1.5396215691956376), Point{Float64}(1.7669558663317395, 1.7970779862793953, 1.7692994807221982), Point{Float64}(2.0, 2.0, 2.0)])

In [303]:
p = plot()
plotChainSeries!(P)
display(p)

In [304]:
P = knittingNeedle(2.3)
P = PolygonalChain([Point(Float64,p) for p in P.vertices]);

In [305]:
Q = helixify(P,4,r=1e-2);

In [306]:
p = plot()
plotChainSeries!(Q)
display(p)

In [307]:
ndens=[5,2,2,2,5]
Q = helixify(P,ndens,r=5e-3);
ls,bas,das = internalCoordinates(Q);

In [308]:
p = plot()
plotChainSeries!(Q)
display(p)

In [8]:
using BenchmarkTools

In [187]:
ndens=[5,2,2,2,5]
Q = helixify(P,ndens,r=5e-3);
ls,bas,das = internalCoordinates(Q);

In [310]:
sum(helixifiedConstraints(Q,ndens,ls,bas,das))

0.0

In [311]:
ener_grad = deriv(tangentEnergyFrac,Q)

66-element Vector{Float64}:
     1.4694738622003392
    -0.561059711010469
    -1.23183641458268
    12.323617911884256
     1.620606841995702
    -9.63883228825638
   -44.47752489624526
   113.62793616507089
    47.31856500572307
    36.317461453476966
  -134.2562641352297
  -140.88684240108373
 -2149.4679253126737
     ⋮
  -175.0761493060288
    13.470090010694008
   -83.27309073769719
    54.57187232426337
   -66.20975223139051
    36.56324891928105
    -8.325501113716674
    -5.270136456835669
    -7.5688249985438105
    -1.3338550483124343
    -0.35708624253732285
    -1.6037621472035042

In [312]:
Al = Aline(Q)

66×66 Base.Matrix{Float64}:
  29.7908       0.0          0.0        …    0.0           0.0
   0.0         29.7908       0.0             0.0429025     0.0
   0.0          0.0         29.7908          0.0           0.0429025
 -29.1859      -0.0         -0.0             0.0           0.0
  -0.0        -29.1859      -0.0             0.0140968     0.0
  -0.0         -0.0        -29.1859     …    0.0           0.0140968
  -7.78979     -0.0         -0.0             0.0           0.0
  -0.0         -7.78979     -0.0             0.0139355     0.0
  -0.0         -0.0         -7.78979         0.0           0.0139355
   5.94181      0.0          0.0             0.0           0.0
   0.0          5.94181      0.0        …    0.00443491    0.0
   0.0          0.0          5.94181         0.0           0.00443491
   1.05384      0.0          0.0            -0.0          -0.0
   ⋮                                    ⋱                  ⋮
   0.0133028    0.0          0.0             0.0           0.0
   0

In [313]:
C =  helixifiedConstraintsJacobian(Q,ndens)

48×66 Base.Matrix{Float64}:
   0.685976    -0.445143   -0.575573  …     0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0       …     0.0         0.0         0.0
  -1.88627     -0.859465   -1.58338         0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   0.0          0.0         0.0       …     0.0         0.0         0.0
 -52.2937    -540.455     355.659           0.0         0.0         0.0
   0.0          0.0         0.0             0.0         0.0         0.0
   ⋮                                

In [314]:
k = 0
for nden in ndens 
    nloc = nden+1 # length of helix
    k += 3*nloc-3
end
T= Float64; 

In [315]:
mat = vcat(
        hcat(Al,transpose(C)),
        hcat(C,zeros(T,k,k))
    )

114×114 Base.Matrix{Float64}:
  29.7908     0.0        0.0      …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
   0.0       29.7908     0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
   0.0        0.0       29.7908      0.0  0.0  0.0  0.0  0.0  0.0  0.0
 -29.1859    -0.0       -0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
  -0.0      -29.1859    -0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
  -0.0       -0.0      -29.1859   …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
  -7.78979   -0.0       -0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
  -0.0       -7.78979   -0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
  -0.0       -0.0       -7.78979     0.0  0.0  0.0  0.0  0.0  0.0  0.0
   5.94181    0.0        0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
   0.0        5.94181    0.0      …  0.0  0.0  0.0  0.0  0.0  0.0  0.0
   0.0        0.0        5.94181     0.0  0.0  0.0  0.0  0.0  0.0  0.0
   1.05384    0.0        0.0         0.0  0.0  0.0  0.0  0.0  0.0  0.0
   ⋮                              ⋱            

In [316]:
size(ener_grad)

(66,)

In [317]:
ener_grad_ext = vcat(ener_grad,zeros(T,k))

114-element Vector{Float64}:
     1.4694738622003392
    -0.561059711010469
    -1.23183641458268
    12.323617911884256
     1.620606841995702
    -9.63883228825638
   -44.47752489624526
   113.62793616507089
    47.31856500572307
    36.317461453476966
  -134.2562641352297
  -140.88684240108373
 -2149.4679253126737
     ⋮
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0
     0.0

In [318]:
rank(C)

48

In [319]:
cons_proy_dir = IterativeSolvers.cg(mat,ener_grad_ext,reltol=1e-10,maxiter=10000,log=false)

114-element Vector{Float64}:
    0.10540129029542798
    1.4431128745486261
   -1.1406993820917435
    0.045023694856885135
    0.6428007522824439
   -0.5937037308509538
    0.00034283611805831785
    0.003977721815266389
   -0.1530670535154096
   -0.017150472725852187
   -0.35513800405222673
    0.10335046700279996
   -0.0032503129310941844
    ⋮
  -56.716624193395425
   15.52032008578733
    2.3107528850142645
   -2.6520710632098288
 -231.74146900640537
  -27.325193117650986
   -3.0286998591952066
   -0.327952951557614
    0.13337650114359556
   -1.0656893658523472
   -0.31083452443350135
   -0.03404884402465382

In [322]:
aux = IterativeSolvers.cg(mat,ener_grad_ext,reltol=1e-10,maxiter=10000,log=true)

([0.10540129029542798, 1.4431128745486261, -1.1406993820917435, 0.045023694856885135, 0.6428007522824439, -0.5937037308509538, 0.00034283611805831785, 0.003977721815266389, -0.1530670535154096, -0.017150472725852187  …  2.3107528850142645, -2.6520710632098288, -231.74146900640537, -27.325193117650986, -3.0286998591952066, -0.327952951557614, 0.13337650114359556, -1.0656893658523472, -0.31083452443350135, -0.03404884402465382], Converged after 2928 iterations.)

In [323]:
norm(mat*aux[1] - ener_grad_ext)

4.959760342206668e-7

In [325]:
n = length(Q)

21

In [328]:
new_chain = toArray(Q)-1e-3*cons_proy_dir[1:(3*n+3)]

66-element Vector{Float64}:
  1.5525159019876174
 -0.5365239817264905
 -0.4774433879290455
  1.2895892569824363
 -0.3650662053273424
 -0.25732918904284546
  1.0277768048388112
 -0.19327260060369655
 -0.0361867821808872
  0.7678941913364138
 -0.02089732415213551
  0.1867365331460043
  0.5102399635618896
  ⋮
  0.1944707030154405
  0.1459723769874607
  0.1921628701497826
 -0.07476699681861407
  0.18923984387488332
 -0.07725494641975837
 -0.344355925693048
  0.2298505936986335
 -0.34676406899964185
 -0.6141476367385788
  0.2689274872096349
 -0.6163259071191731

In [329]:
cons   = helixifiedConstraints(new_chain,ndens,ls,bas,das)
newSol = vcat(zeros(T,3*n+3),-1*cons)
chain_proy_dir = IterativeSolvers.minres(mat,newSol,maxiter=length(mat),reltol=1e-10)

114-element Vector{Float64}:
 -0.00010084784981871164
 -5.437722984205173e-5
 -7.054193343575302e-5
 -5.2934082385112795e-5
 -2.9729838996318803e-5
 -3.463727678525886e-5
 -1.4083782536096718e-5
 -1.0104643426629016e-5
 -5.248034613267906e-6
  9.068718179215159e-6
  8.214208998574241e-7
  1.2855607072453589e-5
  1.4095891375085585e-5
  ⋮
  0.0032942000346573084
  0.000835266561510215
  5.0771024453622496e-5
 -0.001243956751540457
 -0.004777437044904318
 -0.004209485220765505
 -0.0018148124881159034
 -0.0003778976192879938
  2.684727086090065e-6
  4.228300494261948e-6
  2.5465347936665302e-6
  3.6894669688491577e-7

In [330]:
new_chain = new_chain + chain_proy_dir[1:(3*n+3)]
c = 0
cons = helixifiedConstraints(new_chain,ndens,ls,bas,das)
con_norm = LinearAlgebra.norm(cons,2)

3.2973151751106325e-6

In [284]:
using Dierckx

In [285]:
aux = to2DArray(P)

6×3 Base.Matrix{Float64}:
  2.02516  -0.850105  -0.887813
  0.0       0.5        0.866025
  0.0       0.0        0.0
  1.0       0.0        0.0
  1.0       0.0        1.0
 -1.10674   0.351123  -1.10674

In [290]:
val = size(aux,1)

6

In [293]:
spl =ParametricSpline(1:val,aux')

ParametricSpline(knots=[1.0, 3.0, 4.0, 6.0], k=3, extrapolation="nearest", residual=0.0)

In [294]:
xyz = evaluate(spl,LinRange(1,val,40))

3×40 Base.Matrix{Float64}:
  2.02516    1.62774    1.27373    …  -0.321189    -0.690894  -1.10674
 -0.850105  -0.463201  -0.152084       0.185061     0.259703   0.351123
 -0.887813  -0.373698   0.0386481      0.00743762  -0.488195  -1.10674

In [296]:
altQ = PolygonalChain(reshape(xyz,length(xyz)));

In [297]:
p = plot()
plotChainSeries!(altQ)
display(p)